PDF=pdflatex
BIB=bibtex
INDX=makeindex
PDF_ARGS=-interaction nonstopmode
all: clean thesis.tex
	$(PDF) thesis.tex
	$(BIB) thesis
	$(PDF) thesis.tex
	$(PDF) thesis.tex
nostop: thesis.tex
	$(PDF) $(PDF_ARGS) thesis.tex
	$(BIB) thesis
	$(PDF) $(PDF_ARGS) thesis.tex
	$(PDF) $(PDF_ARGS) thesis.tex
clean:
	rm -f *.{ps,log,aux,out,dvi,bbl,blg,idx,ilg,ind,lof,lot,toc}
	rm -f thesis.pdf


